### ISSUE TITLE
Heads are sometimes invisible on remote players

### ISSUE THREAD

**Issue by misternebula** [qsb-dev/quantum-space-buddies#655]

**Comment by xen-42** [comment]
The issue seems to be with `SetHelmetInstance(false)` being called. Can reproduce by having the host be wearing a suit without a helmet and then having somebody else join during that time.

![image](https://github.com/qsb-dev/quantum-space-buddies/assets/22628069/62cd516e-1ade-4076-bbbd-2f2e36937b03)
